<<<<<<< HEAD
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: mahdi
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
=======
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
name:
  value: mahdi
spring:
  cloud:
    config:
      override-system-properties: false

management:
  tracing:
    sampling:
>>>>>>> fab77304475c73e6ab9327d90f384b997d38136b
      probability: 1.0